DROP DATABASE IF EXISTS esquema_biblioteca;
CREATE DATABASE IF NOT EXISTS esquema_biblioteca;
USE esquema_biblioteca;

CREATE TABLE IF NOT EXISTS usuarios(
id_usuario INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
apellido VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE,
contrasena VARCHAR(225) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS autores(
id_autor INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
apellido VARCHAR(100) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS generos(
id_genero INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS libros(
id_libro INT AUTO_INCREMENT PRIMARY KEY,
titulo VARCHAR(100) NOT NULL,
autor_id INT NOT NULL,
FOREIGN KEY (autor_id) REFERENCES autores(id_autor)
ON DELETE CASCADE ON UPDATE CASCADE,
genero_id INT NOT NULL,
FOREIGN KEY (genero_id) REFERENCES generos(id_genero)
ON DELETE CASCADE ON UPDATE CASCADE,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS favoritos(
id INT AUTO_INCREMENT PRIMARY KEY,
libro_id INT NOT NULL,
FOREIGN KEY (libro_id) REFERENCES libros(id_libro)
ON DELETE CASCADE ON UPDATE CASCADE,
usuario_id INT NOT NULL,
FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario)
ON DELETE CASCADE ON UPDATE CASCADE,
UNIQUE (libro_id, usuario_id),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);